import { DatePipe, NgClass } from '@angular/common'
import { Component, OnInit, computed, inject, signal } from '@angular/core'
import { FormsModule } from '@angular/forms'
import { SystemService } from '../../core/api/system.service'
import type { EquipmentResponse, LabRoomResponse, WaitlistResponse } from '../../core/api/system.models'
import { DataStateComponent } from '../../shared/ui/data-state'
import { IconComponent } from '../../shared/ui/icon'
import { PageHeaderComponent } from '../../shared/ui/page-header'
import { StatusBadgeComponent } from '../../shared/ui/status-badge'
import { ToastService } from '../../shared/ui/toast.service'
import { toIso, toLocalDateTimeInput } from '../../shared/utils/presentation'

@Component({selector:'app-waitlists-management-page',imports:[DatePipe,NgClass,FormsModule,PageHeaderComponent,IconComponent,StatusBadgeComponent,DataStateComponent],template:`<section class="space-y-6"><app-page-header title="Quản lý hàng chờ" subtitle="Theo dõi thứ tự, thông báo người tiếp theo, hết hạn hoặc hủy lượt trong phạm vi quản lý."/>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@for(tab of tabs;track tab.value){<button class="kpi-card text-left transition hover:-translate-y-1" (click)="status=tab.value"><p class="text-xs font-bold text-slate-400">{{tab.label}}</p><p class="mt-2 text-3xl font-black" [ngClass]="tab.className">{{count(tab.value)}}</p></button>}</div>
<div class="filter-bar md:grid-cols-2 xl:grid-cols-[1fr_1fr_1fr_1fr_auto]"><div><label class="field-label">Phòng lab</label><select class="input-shell" [(ngModel)]="labId" (ngModelChange)="equipmentId=null"><option [ngValue]="null">Tất cả phòng</option>@for(lab of labs();track lab.labId){<option [ngValue]="lab.labId">{{lab.labName}}</option>}</select></div><div><label class="field-label">Thiết bị</label><select class="input-shell" [(ngModel)]="equipmentId"><option [ngValue]="null">Tất cả thiết bị</option>@for(eq of equipmentOptions();track eq.equipmentId){<option [ngValue]="eq.equipmentId">{{eq.equipmentName}}</option>}</select></div><div><label class="field-label">Khung giờ bắt đầu</label><input class="input-shell" type="datetime-local" [(ngModel)]="requestedStart"/></div><div><label class="field-label">Khung giờ kết thúc</label><input class="input-shell" type="datetime-local" [(ngModel)]="requestedEnd"/></div><div class="flex items-end"><button class="btn-primary w-full" (click)="loadQueue()"><app-icon name="filter" [size]="17"/> Lọc queue</button></div></div>
<article class="card-surface overflow-hidden"><header class="flex items-center justify-between border-b border-slate-100 px-5 py-5"><div><h2 class="font-black text-slate-950">Danh sách hàng chờ</h2><p class="mt-1 text-xs text-slate-400">{{filtered().length}} bản ghi</p></div><div class="flex gap-2"><button class="btn-secondary" (click)="loadAll()"><app-icon name="refresh" [size]="16"/> Toàn bộ</button><button class="btn-primary" [disabled]="!canNotify()" (click)="notifyNext()"><app-icon name="bell" [size]="16"/> Thông báo người tiếp theo</button></div></header>@if(loading()){<div class="p-6"><div class="skeleton h-80 rounded-2xl"></div></div>}@else if(filtered().length===0){<div class="p-6"><app-data-state title="Hàng chờ đang trống" message="Không có bản ghi phù hợp với trạng thái hoặc bộ lọc queue." icon="clock"/></div>}@else{<div class="overflow-x-auto"><table class="table-shell"><thead><tr><th>Vị trí</th><th>Waitlist</th><th>Người dùng</th><th>Tài nguyên</th><th>Khung giờ</th><th>Thông báo</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>@for(item of filtered();track item.waitlistId){<tr><td><span class="flex h-10 min-w-10 items-center justify-center rounded-2xl bg-violet-50 px-3 font-black text-violet-700">#{{item.queuePosition}}</span></td><td class="font-black text-slate-900">#WL-{{item.waitlistId}}</td><td>User #{{item.userId}}</td><td><p class="font-bold text-slate-800">{{resourceName(item)}}</p></td><td><p class="font-bold text-slate-700">{{item.requestedStart|date:'HH:mm dd/MM'}}</p><p class="mt-1 text-xs text-slate-400">{{item.requestedEnd|date:'HH:mm dd/MM'}}</p></td><td>{{item.notifiedAt?(item.notifiedAt|date:'HH:mm dd/MM/yyyy'):'—'}}</td><td><app-status-badge [value]="item.status" domain="waitlist"/></td><td><div class="flex gap-2">@if(item.status==='Waiting'||item.status==='Notified'){<button class="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-rose-200 bg-rose-50 text-rose-700" title="Hủy" (click)="cancel(item)"><app-icon name="x" [size]="16"/></button>}@if(item.status==='Notified'){<button class="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-amber-200 bg-amber-50 text-amber-700" title="Cho hết hạn" (click)="expire(item)"><app-icon name="clock" [size]="16"/></button>}</div></td></tr>}</tbody></table></div>}</article></section>`})
export class WaitlistsManagementPage implements OnInit{
private readonly api=inject(SystemService);private readonly toast=inject(ToastService);protected readonly items=signal<WaitlistResponse[]>([]);protected readonly labs=signal<LabRoomResponse[]>([]);protected readonly equipments=signal<EquipmentResponse[]>([]);protected readonly loading=signal(true);protected status='';protected labId:number|null=null;protected equipmentId:number|null=null;protected requestedStart=toLocalDateTimeInput(new Date(Date.now()+24*60*60_000));protected requestedEnd=toLocalDateTimeInput(new Date(Date.now()+26*60*60_000));protected readonly tabs=[{value:'',label:'Tất cả',className:'text-slate-950'},{value:'Waiting',label:'Đang chờ',className:'text-amber-600'},{value:'Notified',label:'Đã thông báo',className:'text-emerald-600'},{value:'Booked',label:'Đã booking',className:'text-indigo-600'},{value:'Expired',label:'Hết hạn',className:'text-rose-600'}]
protected readonly equipmentOptions=computed(()=>this.labId?this.equipments().filter(x=>x.labId===this.labId):this.equipments());protected readonly filtered=computed(()=>this.items().filter(x=>!this.status||x.status===this.status).sort((a,b)=>a.queuePosition-b.queuePosition))
ngOnInit():void{this.api.labs().subscribe(x=>this.labs.set(x));this.api.equipments().subscribe(x=>this.equipments.set(x));this.loadAll()}
protected count(status:string):number{return status?this.items().filter(x=>x.status===status).length:this.items().length}
protected resourceName(item:WaitlistResponse):string{if(item.labId)return this.labs().find(x=>x.labId===item.labId)?.labName??`Phòng #${item.labId}`;return this.equipments().find(x=>x.equipmentId===item.equipmentId)?.equipmentName??`Thiết bị #${item.equipmentId}`}
protected canNotify():boolean{return Boolean((this.labId||this.equipmentId)&&this.requestedStart&&this.requestedEnd)}
protected loadAll():void{this.loading.set(true);this.api.waitlists().subscribe({next:x=>{this.items.set(x);this.loading.set(false)},error:()=>{this.loading.set(false);this.toast.error('Không tải được hàng chờ')}})}
protected loadQueue():void{if(!this.requestedStart||!this.requestedEnd){this.loadAll();return}this.loading.set(true);this.api.waitlistQueue({labId:this.labId??undefined,equipmentId:this.equipmentId??undefined,requestedStart:toIso(this.requestedStart),requestedEnd:toIso(this.requestedEnd)}).subscribe({next:x=>{this.items.set(x);this.loading.set(false)},error:()=>{this.loading.set(false);this.toast.error('Không tải được queue')}})}
protected notifyNext():void{this.api.notifyNextWaitlist({labId:this.labId,equipmentId:this.equipmentId,requestedStart:toIso(this.requestedStart),requestedEnd:toIso(this.requestedEnd)}).subscribe({next:()=>{this.toast.success('Đã thông báo người tiếp theo');this.loadQueue()},error:()=>this.toast.error('Không thể thông báo người tiếp theo')})}
protected cancel(item:WaitlistResponse):void{if(!confirm(`Hủy waitlist #${item.waitlistId}?`))return;this.api.cancelWaitlist(item.waitlistId).subscribe({next:()=>{this.toast.success('Đã hủy waitlist');this.loadAll()},error:()=>this.toast.error('Không thể hủy waitlist')})}
protected expire(item:WaitlistResponse):void{if(!confirm(`Cho hết hạn waitlist #${item.waitlistId}?`))return;this.api.expireWaitlist(item.waitlistId).subscribe({next:()=>{this.toast.success('Đã cho hết hạn');this.loadAll()},error:()=>this.toast.error('Không thể cho hết hạn')})}
}
